name: Test report
on:
  push:
    branches:
      - main,
      - master

jobs:
  test-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: dotnet test --collect:"XPlat Code Coverage"

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: ./CustomerLibrary.Tests/TestResults/**/coverage.cobertura.xml